DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS question;

CREATE TABLE user (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  email TEXT UNIQUE NOT NULL,
  username TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL
);

CREATE TABLE question (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  author_id INTEGER NOT NULL,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  question_text TEXT NOT NULL,
  corr_ans TEXT NOT NULL,
  dummy1 TEXT NOT NULL,
  dummy2 TEXT NOT NULL,
  dummy3 TEXT NOT NULL,
  FOREIGN KEY (author_id) REFERENCES user (id)
);